version: "3.7"

services:
  app:
    build:
      context: .
#    ports:
#    - "888:5000"
    volumes:
    - ./backend:/app
    - ./app/node_modules
    restart: on-failure
    command: >
      node app.js
  db:
    image: mongo
    env_file:
      - .env
    restart: on-failure
    ports:
    - "27017:27017"
    volumes:
    - ./mongo-db:/data/db
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
